services:
  postgres:
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - backend
      - development

  redis:
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - backend
      - development

networks:
  development:
